Cloud/flask_app/__init__.py
import os
from flask import Flask
from sassutils.wsgi import SassMiddleware

def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        DATABASE=os.path.join(app.instance_path, "flaskr.sqlite"),
    )

    app.wsgi_app = SassMiddleware(
        app.wsgi_app,
        {
            "flask_app": {
                "sass_path": "static/sass",
                "css_path": "static/css",
                "wsgi_path": "/static/css",
                "strip_extension": True,
            }
        },
    )

    from flask_app.views import views
    from flask_app.api import api

    app.register_blueprint(views)
    app.register_blueprint(api, url_prefix="/api")

    from . import db

    db.init_app(app)

    return app

Cloud/flask_app/views.py
from datetime import date
from flask import Blueprint, render_template, Response, request
from jinja2.utils import consume

from flask_app.db import query_db

from io import BytesIO
from matplotlib.figure import Figure
from matplotlib.dates import ConciseDateFormatter, AutoDateLocator
from matplotlib.backends.backend_svg import FigureCanvasSVG

views = Blueprint("views", __name__)


@views.route("/")
def index():

    data = query_db(
        "SELECT *, "
        "max(time_updated) AS 'fill_updated [timestamp]'"
        "FROM fill_level "
        "NATURAL JOIN bin "
        "GROUP BY bin_name"
    )
    return render_template("index.html", data=data)


@views.route("/bin/<name>")
def bin_page(name):
    date_range = request.args.get("date_range") or "2"

    data = query_db(
        "SELECT *, "
        "max(time_updated) AS 'fill_updated [timestamp]'"
        "FROM fill_level "
        "NATURAL JOIN bin "
        "WHERE bin_name = ?",
        [name],
        True,
    )

    fill_history_2days = query_db(
        "SELECT * FROM fill_level WHERE "
        "bin_name = ? "
        "AND time_updated > datetime('now', '-2 days') "
        "ORDER BY time_updated ASC",
        [name],
    )

    exceed_70 = []

    for i in range(1, len(fill_history_2days)):
        if (
            fill_history_2days[i]["fill_percent"] >= 70
            and fill_history_2days[i - 1]["fill_percent"] < 70
        ):
            exceed_70.append(dict(fill_history_2days[i]))

    return render_template(
        "/bin/index.html",
        data=data,
        bin_name=name,
        exceed_70=exceed_70,
        date_range=date_range,
    )


@views.route("/floorplan")
def floorplan():
    data = query_db(
        "SELECT *, "
        "max(time_updated) AS time_updated "
        "FROM fill_level GROUP BY bin_name"
    )
    data = {x["bin_name"]: x["fill_percent"] for x in data}

    return render_template("/floorplan.html", data=data)


@views.route("/fill-chart/<name>/<date_range>")
def fill_chart(name, date_range):
    query = "SELECT bin_name, time_updated, fill_percent FROM bin NATURAL JOIN fill_level WHERE bin_name = ?"

    if date_range == "2":
        query += " AND time_updated > datetime('now', '-2 days')"

    data = query_db(query, [name])

    x = [row["time_updated"] for row in data]
    y = [row["fill_percent"] for row in data]

    # Generate the figure **without using pyplot**.
    fig = Figure()
    ax = fig.add_subplot(1, 1, 1)

    # hide top and right axis
    ax.spines["right"].set_visible(False)
    ax.spines["top"].set_visible(False)
    # HACKY WARNING show date as chart tiile
    # ax.set_title(data[0]["time_updated"].strftime("%A, %d %b %Y"), fontsize="medium")

    ax.set_ylabel("Fiil percent")
    ax.set_ylim([0, 100])

    # x axis interval and format
    locator = AutoDateLocator()
    ax.xaxis.set_major_locator(locator)
    ax.xaxis.set_major_formatter(ConciseDateFormatter(locator))
    fig.autofmt_xdate()

    # plot data
    ax.plot_date(x, y, "-")

    # Save it to a temporary buffer.
    output = BytesIO()
    FigureCanvasSVG(fig).print_svg(output)
    # Embed the result in the html output.
    return Response(output.getvalue(), mimetype="image/svg+xml")

Cloud/flask_app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Smart Bin System</title>
    <meta name="description" content="Smart Bin System Dashboard" />

    <link
      href="{{ url_for('static', filename='css/style.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='favicon.ico') }}"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-3">
      <div class="container">
        <a class="navbar-brand" href="/">Smart Bin System</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/floorplan" id="floorplan-nav-anchor">Floorplan</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">{% block content %}{% endblock %}</div>

    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  </body>
</html>

Cloud/flask_app/templates/floorplan.html
{% from "macros/bin_graphic_fp.html" import bin_graphic_fp with context %}

{% extends "base.html" %}

{% block content %}

<div class="row">
  <?xml version="1.0" encoding="utf-8"?>
  <svg viewBox="0 0 500 350" xmlns="http://www.w3.org/2000/svg">
    <rect
      x="18.692"
      y="31.376"
      width="458.611"
      height="277.036"
      style="fill: none; stroke: rgb(0, 0, 0); stroke-width: 2px"
    />
    <rect
      x="18.024"
      y="196.633"
      width="124.833"
      height="111.482"
      style="fill: none; stroke: rgb(0, 0, 0)"
    />
    <rect
      x="18.024"
      y="196.633"
      width="124.833"
      height="111.482"
      style="fill: none; stroke: rgb(0, 0, 0)"
    />
    <rect
      x="142.857"
      y="196.633"
      width="124.833"
      height="111.482"
      style="fill: none; stroke: rgb(0, 0, 0)"
    />
    <rect
      x="351.802"
      y="196.298"
      width="124.833"
      height="111.482"
      style="fill: none; stroke: rgb(0, 0, 0)"
    />
    <rect
      x="19.359"
      y="31.079"
      width="241.655"
      height="97.463"
      style="fill: none; stroke: rgb(0, 0, 0)"
    />
    <rect
      x="-400.534"
      y="31.079"
      width="139.52"
      height="97.463"
      style="fill: none; stroke: rgb(0, 0, 0)"
      transform="matrix(-1, 0, 0, 1, 0, 0)"
    />

    <!-- bins -->
    {{bin_graphic_fp("/bin/ALPHA", 24.032, 37.309, data["ALPHA"])}}
    <text style="transform: translate(48px, 52px);font-size: 12px">{{data["ALPHA"]}}%</text>
    
    {{bin_graphic_fp("/bin/BRAVO", 266.355, 37.977, data["BRAVO"])}}
    <text style="transform: translate(291px, 52px);font-size: 12px;">{{data["BRAVO"]}}%</text>

    {{bin_graphic_fp("/bin/CHARLIE", 451.268, 35.307, data["CHARLIE"])}}
    <text style="transform: translate(425px, 50px);font-size: 12px;">{{data["CHARLIE"]}}%</text>

    {{bin_graphic_fp("/bin/DELTA", 27.37, 282.302, data["DELTA"])}}
    <text style="transform: translate(51px, 296px);font-size: 12px;">{{data["DELTA"]}}%</text>

    {{bin_graphic_fp("/bin/ECHO", 147.529, 281.636, data["ECHO"])}}
    <text style="transform: translate(172px, 296px);font-size: 12px;">{{data["ECHO"]}}%</text>

    {{bin_graphic_fp("/bin/ALPHA", 272.362, 282.303, data["ALPHA"])}}
    <text style="transform: translate(296px, 297px);font-size: 12px;">{{data["ALPHA"]}}%</text>

    {{bin_graphic_fp("/bin/BRAVO", 449.265, 282.971, data["BRAVO"])}}
    <text style="transform: translate(423px, 298px);font-size: 12px;">{{data["BRAVO"]}}%</text>
  </svg>
</div>

<script>
  document.getElementById("floorplan-nav-anchor").classList.add("active");
</script>
{% endblock %}

Cloud/flask_app/templates/index.html
{% from "macros/bin.html" import bin with context %}

{% extends "base.html" %}

{% block content %}

<div class="row">
  {% for row in data %}
  <div class="col-sm-6 col-md-4 col-lg-3">
    {{bin(row['fill_percent'], row['bin_name'], row['fill_updated'],
    row['is_spill'], row['is_spill_updated'],row['is_tilt'],
    row['is_tilt_updated'] )}}
  </div>
  {% endfor %}
</div>

{% endblock %}

Cloud/flask_app/templates/macros/bin.html
{% from "macros/bin_graphic.html" import bin_graphic with context %}

{% macro bin(fill_percent, name, fill_updated, is_spill, spill_updated, is_tilt, tilt_updated) %}
<a href="{{url_for('views.bin_page', name=name)}}" class="text-decoration-none text-dark">
  <div class="bin-wrapper">
    {{bin_graphic(fill_percent)}}
    
    <h5 class="mb-3">{{name}}</h5>
    <p class="mb-1"><strong> {{fill_percent}}% </strong> full</p>
    
    <p class="text-center mb-1">
      {% if is_spill %}
      <strong>💧 Spill detected!</strong>
      {% else %}
      No spill detected
      {% endif %}
    </p>
    
    <p class="text-center mb-1">
      {% if is_tilt %}
      <strong>Tilt detected!</strong>
      {% else %}
      No tilt detected
      {% endif %}
    </p>
    <span class="bin-arrow">➜</span>
  </div>
</a>
{%endmacro %}

Cloud/flask_app/templates/macros/bin_graphic.html
{% macro bin_graphic(fill_percent) %}
<div class="bin">
  <div
    class="{{'fill-red' if fill_percent > 90 else 'fill-orange' if fill_percent > 75 else 'fill-yellow' if fill_percent > 50 else 'fill-blue' if fill_percent > 25 else 'fill-green'}}"
    style="height:{{fill_percent}}%"
  ></div>
</div>
{% endmacro %}

Cloud/flask_app/templates/macros/bin_graphic_fp.html
{% macro bin_graphic_fp(href, x, y, fill_percent) %}
<a href="{{href}}">
    <rect
      class="svg-bin {{'fill-red' if fill_percent > 90 else 'fill-orange' if fill_percent > 75 else 'fill-yellow' if fill_percent > 50 else 'fill-blue' if fill_percent > 25 else 'fill-green'}}"
      x="{{x}}"
      y="{{y}}"
      width="21.362"
      height="19.359"
      style="stroke: rgb(85, 125, 218);"
    />
  </a>
{% endmacro %}